### ISSUE TITLE
why page show "Not Found"

### ISSUE THREAD

**Issue by WnagoiYy** [LaulauChau/turborepo-nestjs-react-template#2]
![image](https://github.com/LaulauChau/turborepo-nestjs-react-template/assets/16523520/1a0e0d1f-9ff6-457a-8a1e-cf001494582d)

**Comment by LaulauChau** [comment]
I didn't create any route in the template, hence why the `not-found` message.

You need to create a route using the appropriate method. I suggest you read the @tanstack/react-router documentation: https://tanstack.com/router/latest/docs/framework/react/quick-start
